POST http://localhost:3000/register

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "Username":"Ipi",
    "Password":"767343"
}

###
GET http://localhost:3000/bye

###
GET http://localhost:3000/
